### ISSUE TITLE
Tela de edição de endereço (configuração checklist)

### ISSUE THREAD

**Issue by diego-drumond** [Hotmart-Org/zum-android#5]
O app deve permitir que o usuário configure os itens que devem aparecer no checklist, exibindo somente os itens que fazem parte do contexto do endereço.

https://docs.google.com/presentation/d/17gGeeS_u0BDub2xQll7QgA8vGnKFb-nRKc9JtG86fTU/edit#slide=id.g13ef1e41c3_0_255

**Comment by hugonardo** [comment]
+1

**Comment by felipemirandareis** [comment]
+1

**Comment by felipearimateia** [comment]
@diego-drumond No layout dessa tela tem um ícone de busca na Toolbar, ela deve pesquisar dentro do conteúdo do checklist?

**Comment by diego-drumond** [comment]
@felipearimateia pode ser uma consulta contextual somente nos itens que já estão na lista. Se preferir podemos quebrar esta tarefa em duas e deixar a pesquisa em outra tarefa.

**Comment by felipearimateia** [comment]
@diego-drumond Pode ser nessa mesmo, vou implementar então.

**Comment by felipearimateia** [comment]
@diego-drumond Cara falta só falta a pesquisa para fazer, você acha melhor fazer o pull request?

**Comment by diego-drumond** [comment]
@felipearimateia pode finalizar sem a pesquisa que eu crio uma outra tarefa só para ela.

**Comment by diego-drumond** [comment]
criada tarefa #12 para pesquisa no checklist
