### ISSUE TITLE
Tela de histórico de verificação

### ISSUE THREAD

**Issue by diego-drumond** [Hotmart-Org/zum-android#6]
O app deve permitir ao usuário visualizar o seu histórico de verificações, para que ele acompanhe todos os monitoramentos realizados ao longo do tempo.

https://docs.google.com/presentation/d/17gGeeS_u0BDub2xQll7QgA8vGnKFb-nRKc9JtG86fTU/edit#slide=id.g13ef1e41c3_0_265

**Comment by felipemirandareis** [comment]
+1

**Comment by diego-drumond** [comment]
tarefa concluída
